FROM 172631448019.dkr.ecr.us-east-1.amazonaws.com/ubuntu2204:2023-08-16-daily

RUN apt-get install \
  bats \
  ca-certificates \
  curl \
  docker-ce-cli \
  docker-buildx-plugin \
  git \
  make \
  openssh-client \
  rsync \
  sudo \
  unzip \
  iputils-ping \
  tcpdump 


RUN /jorb/scripts/install-python.sh --system-default 3.11

RUN python3.11 -m pip install awscli==1.29.6
RUN python3.11 -m pip install pyyaml==6.0.1
RUN python3.11 -m pip install click==8.1.3
RUN python3.11 -m pip install semver==3.0.2

######### install go
ARG GO_VERSION=1.21.3
RUN /jorb/scripts/install-go.sh ${GO_VERSION}
#########

# Set up Gopath.
WORKDIR /go
ENV GOPATH=/go
ENV GOMAXTHREADS=3
ENV PATH="/usr/local/go/bin:$GOPATH/bin:$PATH"
ENV GO=go
